
<script setup>

import { ref } from 'vue';

const numbers = [...Array(22).keys()].filter(num => num !== 7 && num !== 8 && num !== 22);
// Lista dei numeri da cui scegliere casualmente
/* The three dots (...) in this context are used to create a copy of the array generated by the Array(22).keys() call and then expand it into a new array. This technique is known as a "spread operator" in JavaScript.

Here's how it works:

Array(22).keys() creates an iterable object representing the keys (indexes) of the elements in an array of length 22. This iterable is not a true array, but can be converted to one.

[...Array(22).keys()] uses the spread operator to copy the keys from the generated iterable and create a new array. So we get an array that goes from 0 to 21, which represents the indices of an array of length 22.

.filter(num => num !== 7 && num !== 8 && num !== 22) is then applied to this new array to exclude the numbers 7, 8, and 22, returning an array containing only the desired numbers.

Essentially, the three dots (...) are used to convert the iterable to an array and facilitate data manipulation. */
const randomNumber = ref(null);

const generateRandomNumber = () => {
    const randomIndex = Math.floor(Math.random() * numbers.length);
    randomNumber.value = numbers[randomIndex];
};

</script>

<template>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Choose</h1>
                <p>Random Number: {{ randomNumber }}</p>
                <button @click="generateRandomNumber">Generate Random Number</button>
            </div>
        </div>
    </div>
</template>
  
<style scoped></style>
  